---
abstract: "Perl interface to digitalnz.org 's open data api."
author:
  - 'Brenda Wallace <brenda@wallace.net.nz> http://br3nda.com'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-DigitalNZ
no_index:
  directory:
    - inc
requires:
  Carp: 0
  JSON::Any: 1.19
  LWP::UserAgent: 0
  URI::Escape: 0
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 0.12
